[build]
builder = "dockerfile"
dockerfilePath = "packages/public-api/Dockerfile"
watchPatterns = [
  "packages/public-api/**",
  "packages/swapper/**",
  "packages/caip/**",
  "packages/types/**",
  "packages/utils/**",
  "public/generated/generatedAssetData.json"
]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
